# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anthony's Inception
email: ssg.tyrone.rice@gmail.com
description: > # this means to ignore newlines until "baseurl:"
A beginning.
The establishment of an institution or activity.
The first part in a stage of succeeding events.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
