# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anthony's Inception
email: ssg.tyrone.rice@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A realization of a certain method or idea to
  demonstrate its feasibility, or a demonstration in principle, whose purpose
  is to verify that some concept or theory has the potential of being useful, herefore
  a prototype that in and of itself is designed to determine feasibility, which is not akin to represent deliverables.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
